/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Valeria
 */
public class frmBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form frmBiblioteca
     */
    public frmBiblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBiblioteca = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        tdpBiblioteca = new javax.swing.JTabbedPane();
        pnlCanciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCanciones = new javax.swing.JTable();
        btnBuscarCancion = new javax.swing.JButton();
        txtBuscarCancion = new javax.swing.JTextField();
        pnlAlbumes = new javax.swing.JPanel();
        txtBuscarAlbum = new javax.swing.JTextField();
        btnBuscarAlbum = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlbumes = new javax.swing.JTable();
        pnlArtistas = new javax.swing.JPanel();
        lblImagenArtista = new javax.swing.JLabel();
        lblGeneroArtista = new javax.swing.JLabel();
        lblNombreArtsiata = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtBuscarIntegrante = new javax.swing.JTextField();
        btnBuscarIntegrante = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblIntegarntes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBiblioteca.setBackground(new java.awt.Color(204, 190, 255));
        pnlBiblioteca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsuario.setText("Usuario");
        pnlBiblioteca.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        tdpBiblioteca.setBackground(new java.awt.Color(204, 153, 255));

        pnlCanciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255)));
        pnlCanciones.setForeground(new java.awt.Color(204, 153, 255));
        pnlCanciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));

        tblCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255)));
        tblCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Imagen", "Nombre", "Duración", "Favorito"
            }
        ));
        jScrollPane1.setViewportView(tblCanciones);

        pnlCanciones.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 590, 150));

        btnBuscarCancion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarCancion.setText("Buscar");
        pnlCanciones.add(btnBuscarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 30));

        txtBuscarCancion.setForeground(new java.awt.Color(204, 153, 255));
        txtBuscarCancion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));
        pnlCanciones.add(txtBuscarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 30));

        tdpBiblioteca.addTab("Canción", pnlCanciones);

        pnlAlbumes.setBackground(new java.awt.Color(255, 255, 255));
        pnlAlbumes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarAlbum.setForeground(new java.awt.Color(204, 153, 255));
        txtBuscarAlbum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));
        pnlAlbumes.add(txtBuscarAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 30));

        btnBuscarAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarAlbum.setText("Buscar");
        pnlAlbumes.add(btnBuscarAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 30));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));

        tblAlbumes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255)));
        tblAlbumes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Imagen", "Nombre", "Duración", "Favorito"
            }
        ));
        jScrollPane2.setViewportView(tblAlbumes);

        pnlAlbumes.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 590, 150));

        tdpBiblioteca.addTab("Álbum", pnlAlbumes);

        pnlArtistas.setBackground(new java.awt.Color(255, 255, 255));
        pnlArtistas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenArtista.setText("Imagen artista");
        lblImagenArtista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255)));
        pnlArtistas.add(lblImagenArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, 190));

        lblGeneroArtista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGeneroArtista.setText("Género:");
        pnlArtistas.add(lblGeneroArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, 30));

        lblNombreArtsiata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreArtsiata.setText("Nombre:");
        pnlArtistas.add(lblNombreArtsiata, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 30));

        lblGenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGenero.setText("genero");
        pnlArtistas.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, 30));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setText("nombre");
        pnlArtistas.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 30));

        tdpBiblioteca.addTab("Artista", pnlArtistas);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarIntegrante.setForeground(new java.awt.Color(204, 153, 255));
        txtBuscarIntegrante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));
        jPanel5.add(txtBuscarIntegrante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 30));

        btnBuscarIntegrante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarIntegrante.setText("Buscar");
        jPanel5.add(btnBuscarIntegrante, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 30));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255), 2));

        tblIntegarntes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 255)));
        tblIntegarntes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Imagen", "Nombre", "Duración", "Favorito"
            }
        ));
        jScrollPane4.setViewportView(tblIntegarntes);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 590, 150));

        tdpBiblioteca.addTab("Integrantes", jPanel5);

        pnlBiblioteca.add(tdpBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 670, 350));

        getContentPane().add(pnlBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlbum;
    private javax.swing.JButton btnBuscarCancion;
    private javax.swing.JButton btnBuscarIntegrante;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGeneroArtista;
    private javax.swing.JLabel lblImagenArtista;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreArtsiata;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlAlbumes;
    private javax.swing.JPanel pnlArtistas;
    private javax.swing.JPanel pnlBiblioteca;
    private javax.swing.JPanel pnlCanciones;
    private javax.swing.JTable tblAlbumes;
    private javax.swing.JTable tblCanciones;
    private javax.swing.JTable tblIntegarntes;
    private javax.swing.JTabbedPane tdpBiblioteca;
    private javax.swing.JTextField txtBuscarAlbum;
    private javax.swing.JTextField txtBuscarCancion;
    private javax.swing.JTextField txtBuscarIntegrante;
    // End of variables declaration//GEN-END:variables
}
