/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Valeria
 */
public class frmFavoritos extends javax.swing.JFrame {

    /**
     * Creates new form frmFavoritos
     */
    public frmFavoritos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFavoritos = new javax.swing.JPanel();
        lblTituloFavoritos = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scllpAlbumes = new javax.swing.JScrollPane();
        tblAlbumes = new javax.swing.JTable();
        scllpCanciones = new javax.swing.JScrollPane();
        tblCanciones = new javax.swing.JTable();
        lblCanciones = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scllpArtistas = new javax.swing.JScrollPane();
        tblArtistas = new javax.swing.JTable();
        lblArtistas = new javax.swing.JLabel();
        lblEstFavorito = new javax.swing.JLabel();
        lblLogoTitulo = new javax.swing.JLabel();
        lblTituloLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Favoritos");
        setPreferredSize(new java.awt.Dimension(680, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFavoritos.setBackground(new java.awt.Color(204, 190, 255));
        pnlFavoritos.setMinimumSize(new java.awt.Dimension(680, 640));
        pnlFavoritos.setPreferredSize(new java.awt.Dimension(680, 640));
        pnlFavoritos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloFavoritos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloFavoritos.setText("Favoritos");
        pnlFavoritos.add(lblTituloFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 40));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsuario.setText("Usuario");
        pnlFavoritos.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        pnlFavoritos.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 400, 30));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        pnlFavoritos.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 30));

        tblAlbumes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Imagen", "Nombre", "Género", "Ver", "Eliminar"
            }
        ));
        scllpAlbumes.setViewportView(tblAlbumes);

        pnlFavoritos.add(scllpAlbumes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 600, 100));

        tblCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Imagen", "Canción", "Género", "Álbum", "Eliminar"
            }
        ));
        scllpCanciones.setViewportView(tblCanciones);

        pnlFavoritos.add(scllpCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 600, 100));

        lblCanciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCanciones.setText("Canciones");
        pnlFavoritos.add(lblCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Álbumes");
        pnlFavoritos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        tblArtistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Imagen", "Nombre", "Género", "Ver", "Eliminar"
            }
        ));
        scllpArtistas.setViewportView(tblArtistas);

        pnlFavoritos.add(scllpArtistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 600, 100));

        lblArtistas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblArtistas.setText("Artistas");
        pnlFavoritos.add(lblArtistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 70, -1));

        lblEstFavorito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imegenes/estrella (2).png"))); // NOI18N
        pnlFavoritos.add(lblEstFavorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 30, 40));

        lblLogoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imegenes/Untitled (6).png"))); // NOI18N
        lblLogoTitulo.setText("jLabel9");
        pnlFavoritos.add(lblLogoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 90, 40));

        lblTituloLogo.setFont(new java.awt.Font("Segoe Print", 1, 10)); // NOI18N
        lblTituloLogo.setText("Music plux");
        pnlFavoritos.add(lblTituloLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        getContentPane().add(pnlFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFavoritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblArtistas;
    private javax.swing.JLabel lblCanciones;
    private javax.swing.JLabel lblEstFavorito;
    private javax.swing.JLabel lblLogoTitulo;
    private javax.swing.JLabel lblTituloFavoritos;
    private javax.swing.JLabel lblTituloLogo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFavoritos;
    private javax.swing.JScrollPane scllpAlbumes;
    private javax.swing.JScrollPane scllpArtistas;
    private javax.swing.JScrollPane scllpCanciones;
    private javax.swing.JTable tblAlbumes;
    private javax.swing.JTable tblArtistas;
    private javax.swing.JTable tblCanciones;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
