/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Valeria
 */
public class frmGeneroNoDeseado extends javax.swing.JFrame {

    /**
     * Creates new form frmGeneroNoDeseado
     */
    public frmGeneroNoDeseado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGenNoDes = new javax.swing.JPanel();
        lblTituloGenNoDeseados = new javax.swing.JLabel();
        btnBanda = new javax.swing.JButton();
        btnReggaeton = new javax.swing.JButton();
        btnRock = new javax.swing.JButton();
        btnCountry = new javax.swing.JButton();
        btnPop = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblTituloLogo = new javax.swing.JLabel();
        lblLogoTitulo = new javax.swing.JLabel();
        btnNorteno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Géneros no deseados");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGenNoDes.setBackground(new java.awt.Color(204, 190, 255));
        pnlGenNoDes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloGenNoDeseados.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTituloGenNoDeseados.setText(" Género no deseado");
        pnlGenNoDes.add(lblTituloGenNoDeseados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 190, -1));

        btnBanda.setBackground(new java.awt.Color(224, 224, 224));
        btnBanda.setText("Banda");
        pnlGenNoDes.add(btnBanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 150, 30));

        btnReggaeton.setBackground(new java.awt.Color(224, 224, 224));
        btnReggaeton.setText("Reggaetón");
        pnlGenNoDes.add(btnReggaeton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 150, 30));

        btnRock.setBackground(new java.awt.Color(224, 224, 224));
        btnRock.setText("Rock and Roll");
        pnlGenNoDes.add(btnRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 30));

        btnCountry.setBackground(new java.awt.Color(224, 224, 224));
        btnCountry.setText("Country");
        pnlGenNoDes.add(btnCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, 30));

        btnPop.setBackground(new java.awt.Color(224, 224, 224));
        btnPop.setText("POP");
        pnlGenNoDes.add(btnPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 150, 30));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlGenNoDes.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 90, 30));

        lblTituloLogo.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lblTituloLogo.setText("Music plux");
        pnlGenNoDes.add(lblTituloLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        lblLogoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imegenes/Untitled (3).png"))); // NOI18N
        lblLogoTitulo.setText("jLabel9");
        pnlGenNoDes.add(lblLogoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 80));

        btnNorteno.setBackground(new java.awt.Color(224, 224, 224));
        btnNorteno.setText("Norteño");
        pnlGenNoDes.add(btnNorteno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 150, 30));

        getContentPane().add(pnlGenNoDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
      frmMenu menu=new frmMenu();
      menu.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGeneroNoDeseado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGeneroNoDeseado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGeneroNoDeseado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGeneroNoDeseado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGeneroNoDeseado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanda;
    private javax.swing.JButton btnCountry;
    private javax.swing.JButton btnNorteno;
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnReggaeton;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblLogoTitulo;
    private javax.swing.JLabel lblTituloGenNoDeseados;
    private javax.swing.JLabel lblTituloLogo;
    private javax.swing.JPanel pnlGenNoDes;
    // End of variables declaration//GEN-END:variables
}
